widht = float(input())
hight = float(input())
consumption = float(input())
V = float(input())
stock = float(input())
answer_1 = round(widht*hight,2)
answer_2 = round((answer_1 + ((stock/100)*answer_1))/consumption,2)
answer_3= int((answer_2 // V) + 1)
answer_4 = round((answer_3*V) - answer_2,2)
print(answer_1)
print(answer_2)
print(answer_3)
print(answer_4)